### ISSUE TITLE
Add Kubernetes Api server integration

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/prometheus-training#1]
```
  - job_name: panda
    scrape_interval: 2m
    metrics_path: /k8s/clusters/c-5klbq/metrics
    scheme: https
    bearer_token: xxx
    static_configs:
      - targets:
          - rancher.sikahq.com
```
